export const Images = {
  book: require('./image/splash_book.png'),
  bookline: require('./image/bookline.png'),
  onboard1: require('./image/onboard1.png'),
  onboard2: require('./image/onboard2.png'),
  onboard3: require('./image/onboard3.png'),
  politics: require('./image/politics.png'),
  history: require('./image/history.png'),
  science: require('./image/science.png'),
  law: require('./image/law.png'),
  food: require('./image/food.png'),
  medical: require('./image/medical.png'),
  design: require('./image/design.png'),
  culture: require('./image/culture.png'),
  sport: require('./image/sport.png'),
  pink: require('./image/right.png'),
  text: require('./image/text.png'),
};
